site_name: 'Git in 30 Minutes: A Beginner''s Guide for Technical Writers'
site_url: https://www.git30minutes.com
site_description: Free web edition + optional eBook. A concise, practical Git guide
  for technical writers.
theme:
  name: material
  icon:
    logo: material/git
  features:
  - navigation.top
  - navigation.sections
  - navigation.footer
  - content.code.copy
  language: en
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css:
- stylesheets/extra.css
markdown_extensions:
- admonition
- attr_list
- md_in_html
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
nav:
- Home: index.md
- Step 1 - Set Up and Initialize Your Project: 01-setup.md
- Step 2 - Make Your First Commit: 02-first-commit.md
- Step 3- Check Status and Make Changes: 03-status.md
- Step 4 - Branch Out: 04-branching.md
- Step 5 - Collaborate with Remote Repositories: 05-remotes.md
- Where to Go Next: A1-resources.md
- Top 10 Most Commonly Used Git Commands: A2-top10.md
- Example Scenario Using All 10 Commands: A3-example.md
- 10 Most Common Git Problems (and How To Resolve Them): A4-problems.md
- Git Glossary: A5-glossary.md
- Command Line Crash Course: A6-cli.md
- About the Author: A7-about.md
- About this Book: thisbook.md